name: Scheduled Weather LLM Service Run

on:
  schedule:
    # Runs at 6am and 6pm UTC every day
    - cron: '0 6,18 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-weather-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run weather service
        env:
          # Add any environment variables your service needs
          MONGO_URI: ${{ secrets.MONGO_URI }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_URL: ${{ secrets.LLM_API_URL }}
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          # Add other environment variables as needed
        run: |
          python -m app.services.scheduled_task  # Adjust this to the actual script that needs to run